version: '3'
services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=MyG4Q2miMQCBbx
    volumes:
      - /e/postgres_data:/var/lib/postgresql/data
    networks:
      - nextcloud

  redis:
    image: redis:6.2
    restart: always
    volumes:
      - redis_data:/var/lib/redis
    networks:
      - nextcloud

  clamav:
    image: clamav/clamav:stable_base
    restart: always
    volumes:
      - /e/clamav_db:/var/lib/clamav/
    networks:
      - nextcloud

  app:
    image: nextcloud:20-fpm
    restart: always
    environment:
      # db credentials
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=MyG4Q2miMQCBbx
      - POSTGRES_HOST=db
      # # external smtp
      # - SMTP_HOST=your.mail.host
      # - SMTP_SECURE=ssl
      # - SMTP_NAME=admin@your-mail.domain
      # - SMTP_PASSWORD=secret
      # - SMTP_FROM_ADDRESS=your.mail.domain
      # - MAIL_DOMAIN=your-mail-domain
      # redis
      - REDIS_HOST=redis
      # user
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=secret
      - NEXTCLOUD_TRUSTED_DOMAINS=karlms.ca
    volumes:
      - /e/nextcloud:/var/www/html
      - /e/nextcloud-data:/var/www/html/data
    networks:
      - nextcloud

  web:
    image: nginx:latest
    restart: always
    environment:
      # reverse proxy
      - VIRTUAL_HOST=karlms.ca
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=karlms.ca
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /e/nextcloud:/var/www/html
    networks:
      - nextcloud
      - proxynet

  cron:
    image: alpine
    restart: always
    command: sh -c "echo \"*/1 * * * * wget -qO- https://karlms.ca/cron.php\" | crontab - && crond -f -L /dev/stdout"

volumes:
  postgres_data:
  nextcloud_installation:
  redis_data:
  clamav_db:

networks:
  nextcloud:
  proxynet:
    external:
      name: proxynet