version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /e/nginx_certs:/etc/nginx/certs
      - /e/nginx_vhost:/etc/nginx/vhost.d
      - /e/nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'
    networks:
      - proxynet

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /e/nginx_certs:/etc/nginx/certs
      - /e/nginx_vhost:/etc/nginx/vhost.d
      - /e/nginx_html:/usr/share/nginx/html
      - /e/letsencrypt_acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:
  letsencrypt_acme:

networks:
  proxynet:
    external: true