version: '3.6'
networks:
  frontend:
    # add this if the network is already existing!
    external: true
services:
  flame:
    #https://github.com/pawelmalak/flame
      # Has three main pages after domain
      # /settings
      # /applications
      # /bookmarks
    image: pawelmalak/flame
    container_name: flame
    hostname: flame
    volumes:
      - /media/kyle/hcloud/docker/flame/data:/app/data 
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005 #<hostport>:<containerport>
#    secrets:
#      - password # optional but required for (1)
    environment:
      - PASSWORD=flame_password
#      - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped

# optional but required for Docker secrets (1)
#secrets:
#  password:
#    file: /path/to/secrets/password