---
version: "2.1"

networks:
  bridge:
    # add this if the network is already existing!
    external: true
  proxynet:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /e/docker/radarr-sonarr/sonarr/config:/config
      - /d:/media # My Media HD
    networks:
      - proxynet
      - bridge
    ports:
      - 8989:8989
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /e/docker/radarr-sonarr/radarr/config:/config
      - /d:/media # My Media HD
    networks:
      - proxynet
      - bridge
    ports:
      - 7878:7878
    restart: unless-stopped
    
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=false #optional
    volumes:
      - /e/docker/radarr-sonarr/jackett/config:/config
      - /d/downloads:/downloads
    networks:
      - proxynet
      - bridge
    ports:
      - 9117:9117
    restart: unless-stopped