version: '3'
networks:
  frontend:
    # add this if the network is already existing!
    external: true

services:
  nginx-app:
    # https://github.com/NginxProxyManager/nginx-proxy-manager
      # # default account:
        # admin@example.com
        # changeme
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80' #<hostport>:<containerport>
      - '81:81' #<hostport>:<containerport>
      - '443:443' #<hostport>:<containerport>
    container_name: nginx
    hostname: nginx
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npmpsw"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /media/kyle/hcloud/docker/proxy/app/data:/data
      - /media/kyle/hcloud/docker/proxy/app/letsencrypt:/etc/letsencrypt
    networks:
      - frontend
    extra_hosts:
    - "karlms:10.0.0.229"
    restart: always
    
  nginx-db:
    # https://github.com/jc21/docker-mariadb-aria
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npmpsw'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npmpsw'
    container_name: nginx-db
    hostname: nginx-db
    volumes:
      - /media/kyle/hcloud/docker/proxy/db/data/mysql:/var/lib/mysql
    networks:
      - frontend