version: '3'
networks:
  frontend:
    # add this if the network is already existing!
    external: true

services:
# default account:
  # admin@example.com
  # changeme
  nginx-app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    container_name: nginx
    hostname: nginx
    environment:
      DB_MYSQL_HOST: "nginx-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npmpsw"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /e/docker/proxy/app/data:/data
      - /e/docker/proxy/app/letsencrypt:/etc/letsencrypt
    networks:
      - frontend
    extra_hosts:
    - "karlms:10.0.0.229"
    
  nginx-db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npmpsw'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npmpsw'
    container_name: nginx-db
    hostname: nginx-db
    volumes:
      - /e/docker/proxy/db/data/mysql:/var/lib/mysql
    networks:
      - frontend