version: "3"
networks:
  frontend:
    # add this if the network is already existing!
    external: true

services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    hostname: organizr
    volumes:
      - /e/docker/organizr/config:/config
    ports:
      - 5817:80
    networks:
      - frontend
    restart: always
