version: "3"
networks:
  frontend:
    # add this if the network is already existing!
    external: true

services:
  organizr:
    # https://github.com/causefx/Organizr
    image: organizr/organizr:latest
    container_name: organizr
    hostname: organizr
    volumes:
      - /media/kyle/hcloud/docker/organizr/config:/config 
    ports:
      - 5817:80 #<hostport>:<containerport>
    networks:
      - frontend
    restart: unless-stopped
